# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: push-build

# This workflow can be used for pushing to the production server and will only be ran when code is pushed to the main branch

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js dependencies
        run: |
          npm i -g pnpm
          pnpm i

      - name: Build App
        run: pnpm run build

      - name: Zip The Build
        uses: vimtor/action-zip@v1
        with:
          files: dist/
          dest: chat-client-uwu.zip

      - name: Deploy to Server
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: 'chat-client-uwu.zip' 
          remote: '/var/www/test.zip' 
          host: ${{secrets.HOST}}  
          user: ${{secrets.USER}}   
          password: ${{secrets.PASS}}

      - name: unzip
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          script: | 
            unzip -o /var/www/test.zip -d /var/www/test/
            rm -rf /var/www/test.zip