# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Testing

# This workflow can be used for pushing to the production server and will only be ran when code is pushed to the main branch

on:
  push:
    tags:
      - "v*"


jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16-alpine3.12
    steps:
      - uses: actions/checkout@v2

      - name: Install sudo package
        run: apt update && apt install sudo

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Install NPM dependencies
        run: npm ci

      - name: Build App
        run: npm run build
        env:
          VITE_APP_NAME: "Nerimity"
          VITE_SERVER_URL: "https://nerimity.com"
          VITE_APP_URL: "https://nerimity.com"
          VITE_APP_VERSION: ${{ steps.get_version.outputs.VERSION }}
          VITE_MOBILE_WIDTH: 850

      - name: Zip The Build
        uses: vimtor/action-zip@v1
        with:
          files: dist/
          dest: chat-client-${{ steps.get_version.outputs.VERSION }}.zip

      - name: Publish Draft Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          files: |
            chat-client-${{ steps.get_version.outputs.VERSION }}.zip

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: /var/www/nerimity.com/dist